blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/medz/refine-sqlx/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/medz/refine-sqlx#readme
    about: Read the documentation and examples
  - name: 🚀 Refine Framework
    url: https://refine.dev
    about: Learn more about the Refine framework
  - name: 📧 Email Support
    url: mailto:support@refine-orm.dev
    about: Contact us directly for enterprise support or sensitive issues